print('log print')
print('log print 2')
cat('log cat')
cat('log cat 2')
rlang::inform('log inform')
rlang::inform('log inform 2')
message('log message')
message('log message 2')
warning("log warning")
warning("log warning2")
stop("log error")
stop("log error2")
