#' Creation of a log and axecution of a file
#'
#' `axecute()` creates a log, executes a file, and returns 0 if there are no
#' errors or 1 if there are any errors
#'
#' @param file String. Path to file to execute
#' @param log_name String. Name of log file
#' @param log_path String. Path to log file
#' @param include_rds Boolean. Option to export log object as Rds file.
#' Defaults to FALSE
#' @param quit_on_error Boolean. Should the session quit with status 1 on error?
#' Defaults to TRUE
#' @param to_report String vector. Objects to optionally report, may include as
#' many as necessary:
#' * messages: any messages generated by program execution
#' * output: any output generated by program execution
#' * result: any result generated by program execution
#' @param show_repo_url Boolean. Should the repository URLs be reported
#' Defaults to FALSE
#' @param extra_info List. Objects to optionally add on to end of log
#' in a special extra info section. List printed in YAML format. Optional
#' @param execution_method String. How should the logging be executed:
#' * callr: uses callr::r() to create a background session to run script
#' * local: uses source() to run script in current session
#' @param ... Not used
#'
#' @importFrom purrr map_chr
#' @importFrom callr r
#'
#' @return 0 if there are no errors or 1 if there are any errors
#' @export
#'
#' @examples
#' dir <- tempdir()
#' text <- 'print("Hello, logrx-person!")'
#' fileConn <- file(file.path(dir, "hello.R"))
#' writeLines(text, fileConn)
#' close(fileConn)
#'
#' axecute(file.path(dir, "hello.R"))
#'
#'
#' fileConn <- file(file.path(dir, "hello.Rmd"))
#' writeLines(text, fileConn)
#' close(fileConn)
#'
#' axecute(file.path(dir, "hello.Rmd"))
axecute <- function(file,
                    log_name = NA,
                    log_path = NA,
                    include_rds = FALSE,
                    quit_on_error = TRUE,
                    to_report = c("messages", "output", "result"),
                    show_repo_url = FALSE,
                    extra_info = NA,
                    execution_method = "callr",
                    ...) {
  # lower everything for consistency and check values
  to_report <- map_chr(to_report, tolower)
  match.arg(to_report, several.ok = TRUE)

  # create temp run file 
  temp_exec_file <- make_temp_exec_file(file, log_name, log_path, include_rds, quit_on_error, to_report, show_repo_url, extra_info)
  
  # dispatch out to execution method
  if (tolower(execution_method) == "callr") {
    child <- r(function(x) source(x), 
      args = list(temp_exec_file),
      error = "stack", show = TRUE)
  } else if (tolower(execution_method) == "local") {
    source(temp_exec_file)
  } else {
    stop("Currently supported execution methods are callr and local")
  }

  # check for errors prior to log_write() since this can remove the log
  # UPDATE TO READ IN LOG AND CHECK
  #any_errors <- read_log_file()

  # if error, quit with status = 1 if not interactive
  #if (!interactive() & !is.null(any_errors) & quit_on_error) {
  #  quit(status = 1)
  #}
}
