#' Creation of a log and axecution of a file
#'
#' `axecute()` executes a file and creates a log
#'
#' @param file String. Path to file to execute
#' @param log_name String. Name of log file
#' @param log_path String. Path to log file
#' @param include_rds Boolean. Option to export log object as Rds file.
#' Defaults to FALSE
#' @param quit_on_error Boolean. Should the session quit with status 1 on error?
#' Defaults to TRUE
#' @param to_report String vector. Objects to optionally report, may include as
#' many as necessary:
#' * messages: any messages generated by program execution
#' * output: any output generated by program execution
#' * result: any result generated by program execution
#' @param show_repo_url Boolean. Should the repository URLs be reported
#' Defaults to FALSE
#' @param error_on_unapproved Boolean. Should execution be stopped if unapproved
#' packages are detected before running the script? Requires an approved list
#' to be configured via `options(log.rx.approved)`. Defaults to FALSE
#' @param extra_info List. Objects to optionally add on to end of log
#' in a special extra info section. List printed in YAML format. Optional
#' @param ... Not used
#'
#' @section Handling Existing log.rx Environments:
#' If a log.rx environment already exists when `axecute()` is called, the
#' function will detect this and provide helpful guidance on how to resolve
#' the issue. This typically occurs when a previous execution did not complete
#' properly or the environment was not cleaned up.
#'
#' **In interactive mode**, you will be presented with a menu offering two options:
#' \enumerate{
#'   \item Allow logrx to automatically remove the existing environment and
#'         proceed with execution
#'   \item Cancel execution and manually remove the environment using
#'         `log_remove()` or by restarting your R session
#' }
#'
#' **In non-interactive mode** (e.g., batch scripts), an error will be raised
#' with detailed instructions on how to resolve the issue, including using
#' `log_remove()` to programmatically clear the environment or restarting
#' your R session.
#'
#' See the \href{https://pharmaverse.github.io/logrx/articles/execution.html}{Execution vignette}
#' for more details on handling existing environments.
#'
#' @importFrom purrr map_chr
#'
#' @return NULL. Function is called for side effects. In non-interactive sessions,
#'   exits with status 1 if errors occur and \code{quit_on_error} is TRUE.
#' @export
#'
#' @examples
#' dir <- tempdir()
#' text <- 'print("Hello, logrx-person!")'
#' fileConn <- file(file.path(dir, "hello.R"))
#' writeLines(text, fileConn)
#' close(fileConn)
#'
#' axecute(file.path(dir, "hello.R"))
#'
#'
#' fileConn <- file(file.path(dir, "hello.Rmd"))
#' writeLines(text, fileConn)
#' close(fileConn)
#'
#' axecute(file.path(dir, "hello.Rmd"))
axecute <- function(file,
                    log_name = NA,
                    log_path = NA,
                    include_rds = FALSE,
                    quit_on_error = TRUE,
                    to_report = c("messages", "output", "result"),
                    show_repo_url = FALSE,
                    error_on_unapproved = FALSE,
                    extra_info = NA,
                    ...) {
  # deprecations
  if (methods::hasArg(remove_log_object)) {
    lifecycle::deprecate_stop("0.3.0", "axecute(remove_log_object = )", "axecute(include_rds = )")
  }

  # remove log object
  remove_log_object <- TRUE

  # lower everything for consistency and check values
  to_report <- map_chr(to_report, tolower)
  match.arg(to_report, several.ok = TRUE)

  # initialize log
  log_config(
    file = file,
    log_name = log_name,
    log_path = log_path,
    extra_info = extra_info
  )

  # pre-execution approved package check
  if (error_on_unapproved) {
    unapproved_pkgs <- get_pre_execution_packages(file)
    if (!is.null(unapproved_pkgs)) {
      set_log_element("hash_sum", digest::sha1(readLines(file, warn = FALSE)))
      set_log_element("session_info", get_session_info())
      set_log_element("errors", list(message = paste0(
        "Unapproved packages detected prior to execution: ",
        paste(unapproved_pkgs, collapse = ", ")
      )))
      set_log_element("unapproved_packages_functions", data.frame(
        library = paste0("package:", unapproved_pkgs),
        function_name = "",
        stringsAsFactors = FALSE
      ))
      log_write(
        file = file,
        remove_log_object = TRUE,
        show_repo_url = show_repo_url,
        include_rds = include_rds,
        to_report = character(0),
        extra_info = extra_info
      )
      stop(
        "Unapproved packages detected prior to execution: ",
        paste(unapproved_pkgs, collapse = ", "),
        call. = FALSE
      )
    }
  }

  # run the code
  run_safely_loudly(file)

  # check for errors prior to log_write() since this can remove the log
  any_errors <- get_log_element("errors")

  # write log
  log_write(
    file = file,
    remove_log_object = remove_log_object,
    show_repo_url = show_repo_url,
    include_rds = include_rds,
    to_report = to_report,
    extra_info = extra_info
  )

  # if error, quit with status = 1 if not interactive
  if (!interactive() & !is.null(any_errors) & quit_on_error) {
    quit(status = 1)
  }
}
