#' Capture errors, warnings, messages, and a stream output from
#' executing R code
#'
#' @importFrom purrr as_mapper
#'
#' @param code All code to be run loudly
#'
#' @return Wrapped function returns a list with components
#'   `result`, `stream`, `messages` and `warnings`.
#'
#' @noRd
#'
loudly <- function(code) {
  warnings <- character()
  wHandler <- function(w) {
    warnings <<- c(warnings, w$message)
  }

  messages <- character()
  mHandler <- function(m) {
    messages <<- c(messages, m$message)
  }

  temp <- file()
  sink(temp, split = TRUE)
  on.exit({
    sink()
    close(temp)
  })

  result <- withCallingHandlers(
    code,
    warning = wHandler,
    message = mHandler
  )

  output <- paste0(readLines(temp, warn = FALSE), collapse = "\n")

  list(
    result = result,
    output = output,
    warnings = warnings,
    messages = messages
  )
}

#' Dummy function for running a file safely
#' @noRd
run_safely <- function(file) "dummy"

#' Is this a R Markdown file
#' @param file String. Path to file to execute
#' @noRd
is_rmarkdown <- function(file) {
  grepl("*.Rmd$", file, ignore.case = TRUE)
}

#' Dummy function for running a file
#' @noRd
run_file <- function(file) {
  if (is.null(getOption("log.rx.exec.env"))) {
    exec_env <- new.env(parent = globalenv())
  } else {
    exec_env <- getOption("log.rx.exec.env")
  }

  if (is_rmarkdown(file)) {
    rmarkdown::render(file, envir = exec_env)
  } else {
    source(file, local = exec_env)
  }
}

#' Safely run an R script and record results, outputs, messages, errors, warnings
#'
#' @importFrom purrr safely discard
#' @importFrom stringr str_starts
#'
#' @param file File to run
#'
#' @return Nothing
#'
#' @noRd
#'
run_safely_loudly <- function(file) {
  ret <- loudly(run_safely(file))
  set_log_element("messages", discard(ret$messages, ~ str_starts(.x, "Error")))
  set_log_element("output", ret$output)
  set_log_element("result", ret$result$result)
  set_log_element("warnings", ret$warnings)
  set_log_element("errors", ret$result$error)
  set_log_element("hash_sum", digest::sha1(readLines(file, warn = FALSE)))

  # Session Info
  set_log_element("session_info", get_session_info())
}

#' Creation of a execution of a file
#'
#' @param file String. Path to file to execute
#' @param log_name String. Name of log file
#' @param log_path String. Path to log file
#' @param include_rds Boolean. Option to export log object as Rds file.
#' Defaults to FALSE
#' @param quit_on_error Boolean. Should the session quit with status 1 on error?
#' Defaults to TRUE
#' @param to_report String vector. Objects to optionally report, may include as
#' many as necessary:
#' * messages: any messages generated by program execution
#' * output: any output generated by program execution
#' * result: any result generated by program execution
#' @param show_repo_url Boolean. Should the repository URLs be reported
#' Defaults to FALSE
#' @param extra_info List. Objects to optionally add on to end of log
#' in a special extra info section. List printed in YAML format. Optional
#' 
#' @return name of tempfile created for running
#' @export
make_temp_exec_file <- function(file,
                                log_name = NA,
                                log_path = NA,
                                include_rds = FALSE,
                                quit_on_error = TRUE,
                                to_report = c("messages", "output", "result"),
                                show_repo_url = FALSE,
                                extra_info = NA) {
  # make tempfile
  temp_exec <- tempfile(fileext = ".R")
  temp_exec_con <- file(temp_exec)

  # create list of lines for file
  logrx_lines <- c(
    # initialize log
    "logrx::log_config(",
    paste0("file = '", normalizePath(file, winslash = "/"), "',"),
    paste0("log_name = '", log_name, "',"),
    paste0("log_path = '", normalizePath(log_path, winslash = "/"), "',"),
    paste0("extra_info = ", extra_info),
    ")",
    # run the code
    paste0("logrx:::run_safely_loudly('", normalizePath(file, winslash = "/"), "')"),
    # write log
    "logrx::log_write(",
    paste0("file = '", normalizePath(file, winslash = "/"), "',"),
    paste0("show_repo_url = ", show_repo_url, ","),
    paste0("include_rds = ", include_rds, ","),
    #paste0("to_report = ", to_report, ","),
    paste0("extra_info = ", extra_info),
    ")"
  )

  writeLines(logrx_lines, temp_exec_con)
  close(temp_exec_con)

  return(normalizePath(temp_exec, winslash = "/"))
}